kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibp
subjects:
- kind: ServiceAccount
  name: default
  namespace: ibp
roleRef:
  kind: ClusterRole
  name: ibp
  apiGroup: rbac.authorization.k8s.io

